export const ERROR_CODES = {
  AUTH_MISSING_ORIGIN: "AUTH_MISSING_ORIGIN",
  AUTH_GOOGLE_PROVIDER: "AUTH_GOOGLE_PROVIDER",
  AUTH_GOOGLE_REDIRECT_MISSING: "AUTH_GOOGLE_REDIRECT_MISSING",
  AUTH_CALLBACK_MISSING_TOKEN: "AUTH_CALLBACK_MISSING_TOKEN",
  AUTH_CALLBACK_EXCHANGE_FAILED: "AUTH_CALLBACK_EXCHANGE_FAILED",
  AUTH_CALLBACK_USER_MISSING: "AUTH_CALLBACK_USER_MISSING",
  AUTH_CALLBACK_PROFILE_FAILED: "AUTH_CALLBACK_PROFILE_FAILED",
  AUTH_LOCAL_BYPASS_DISABLED: "AUTH_LOCAL_BYPASS_DISABLED",
  AUTH_LOCAL_BYPASS_FAILED: "AUTH_LOCAL_BYPASS_FAILED",
  AUTH_ROUTE_TO_SUMMARY: "AUTH_ROUTE_TO_SUMMARY",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
